### ISSUE TITLE
TypeError: Object.getPrototypeOf called on non-object

### ISSUE THREAD

**Issue by trazek** [kentcdodds/ng-stats#3] opened 2014-10-24 21:55 UTC
I am getting this error when trying to use this module. The error line is: 
#41 -  " var scopePrototype = Object.getPrototypeOf($rootScope);"

The "getRootScope()" method seems to be returning a non-object.

 This line: " var scopeEl = document.querySelector('.ng-scope');"  seems to be failing. My "ng-app" is on the body tag. I tried putting it on the HTML tag with same results.

**Comment by kentcdodds** [comment] 2015-01-07 20:47
I'm going to close this. Let me know if you still have issues with it.

**Closed by kentcdodds** 2015-01-07 20:47 UTC

**Comment by pencilcheck** [comment] 2015-02-08 07:24
Getting this error when I am using with ionic. I create a directive that calls the function 
```
        showAngularStats(
          position: "topleft"
          digestTimeThreshold: 16
          autoload: true
          logDigest: true
          logWatches: true
        )
```
And put it under index.html

All of the above test returns null. And i'm pretty sure angular loads.

**Comment by pencilcheck** [comment] 2015-02-08 07:31
I'm using angular 1.3.x
Could it be the problem with newer angular?

**Comment by kentcdodds** [comment] 2015-02-08 10:20
No, it works fine with my apps on 1.3.x. The code you have there is
invalid... Are you sure you're passing an object to the function? Don't
forget the curly braces...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

I'm using angular 1.3.x
Could it be the problem with newer angular?

—
Reply to this email directly or view it on GitHub
<https://github.com/kentcdodds/ng-stats/issues/3#issuecomment-73400404>.

**Comment by pencilcheck** [comment] 2015-02-09 07:39
Oh, forgot to clarify that the code is in Coffeescript so no need for comma and curly braces :)

**Comment by kentcdodds** [comment] 2015-02-09 09:34
I'm not sure what to tell you without additional information. You may need to step into the script to see what's going on to give me more info. It works fine on any site I use it on.

**Comment by kentcdodds** [comment] 2015-02-09 09:35
Oh, one thing that you'll need to make sure of is that debug info is enabled: https://docs.angularjs.org/guide/production reenable it with: `angular.reloadWithDebugInfo();`

**Comment by marduke182** [comment] 2015-03-17 12:09
@pencilcheck The issue is related to ionic implementation, they remove the ng-scope and ng-isolate-scope. In this line: https://github.com/driftyco/ionic/blob/v1.0.0-rc.0/release/js/ionic-angular.js#L279

**Comment by kentcdodds** [comment] 2015-03-17 12:15
Ah, very interesting! Ping @adamdbradley, @ajoslin, @mhartington, and @mlynch (sorry, don't know which of you is best for this question). I'm very curious to know why this was necessary :-) Seems to me it would just be better to let the user specify `$compileProvider.debugInfoEnabled(false);` when they want to get that perf win.

**Comment by pvadam** [comment] 2015-08-28 13:09
I've sent a pull request which adds basic Ionic support here:
https://github.com/kentcdodds/ng-stats/pull/44
